Assignment 3
FacultadInformatica-LinkedData/Curso2022-2023-ODKG pull request #128
Opened 2022-09-30 10:48 UTC by ershimen

2022-09-30 18:13 UTC, dgarijo requested changes

2022-09-30 18:13 UTC, dgarijo commented on Assignment4/ershimen-180305/task06.py
> +g.add((ns.JohnSmith, vcard.Work, ns.UPM))
vcard.Work does not exist in vcard. Create your own namespace for youw own property if you can't find one

2022-09-30 18:13 UTC, dgarijo commented on Assignment4/ershimen-180305/task07.py
> +    print(s)
missng the subclasses of person

2022-09-30 18:13 UTC, dgarijo commented on Assignment4/ershimen-180305/task07.py
> +    ?Individual rdf:type ns:Person.
missing the individuals belonging to any subclass of person

2022-09-30 18:13 UTC, dgarijo commented on Assignment4/ershimen-180305/task07.py
> +    ?Individual ?Property ?Class
same as above

2022-10-02 12:09 UTC, ocorcho commented
Assignment 3 can be merged.
@dgarijo for assignment 4.

2022-10-02 17:16 UTC, dgarijo commented on Assignment4/ershimen-180305/task07.py
> +      ?SubClass rdfs:subClassOf ns:Person.
Use  * to retrieve the subclass hierarchy.

2022-10-02 17:16 UTC, dgarijo commented on Assignment4/ershimen-180305/task07.py
> +      ?Individual rdf:type ?SubClass.
Same as above

2022-10-02 17:17 UTC, dgarijo requested changes
Small changes requested

2022-10-03 12:52 UTC, merged