Added assignment 2b
FacultadInformatica-LinkedData/Curso2022-2023-ODKG pull request #135
Opened 2022-09-30 13:38 UTC by paumurl

2022-09-30 18:17 UTC, dgarijo commented
@ocorcho

2022-10-02 11:56 UTC, ocorcho commented
Mine are ok. 
@dgarijo check whether there is anything else to check in assignment 4, and accept when ready

2022-10-02 17:54 UTC, dgarijo requested changes
Well done in general. Small changes requested

2022-10-02 17:54 UTC, dgarijo commented on Assignment4/paumurl-e22a302/Task06.py
> +g.add((ns.JohnSmith, FOAF.member, ns.UPM))
the domain of foaf:member is a Group, so this is not correct. (the property is intended to be ns.UPM foaf:member ns:JohnSmith). Well done for searching for alternative properties, but you have to make sure they match your domain/range. If you cannot find one, create your own.

2022-10-02 17:54 UTC, dgarijo commented on Assignment4/paumurl-e22a302/Task08.py
> +      print(s1,p1,o1)
You completed all fields, not the fields you were requested.

2022-10-03 12:47 UTC, dgarijo commented on Assignment4/paumurl-e22a302/Task06.py
> +g.add((ns.JohnSmith, FOAF.member, ns.UPM))
Still not correct

2022-10-03 12:47 UTC, dgarijo requested changes
Still unaddressed comments

2022-10-03 12:48 UTC, dgarijo approved these changes

2022-10-03 12:48 UTC, merged