Assignment4-AndreiSaavedra
FacultadInformatica-LinkedData/Curso2022-2023-ODKG pull request #151
Opened 2022-10-01 17:27 UTC by saavedrAndrei

2022-10-02 17:34 UTC, dgarijo requested changes

2022-10-02 17:34 UTC, dgarijo commented on Assignment4/saavedrAndrei-117032611/task06.py
> +!pip install rdflib
won't work in python. This is notebook magic

2022-10-02 17:34 UTC, dgarijo commented on Assignment4/saavedrAndrei-117032611/task06.py
> +g.add((ns.JohnSmith, vcard.work, ns.UPM))
you are defining the work property in vcard, but it does not exist. Create your own

2022-10-02 17:34 UTC, dgarijo commented on Assignment4/saavedrAndrei-117032611/task07.py
> +      ?subclass rdfs:subClassOf ns:Person .
use * to get all subclass hierarchy

2022-10-02 18:42 UTC, saavedrAndrei commented
Assignment4-Corrected

2022-10-03 13:26 UTC, dgarijo approved these changes

2022-10-03 13:26 UTC, merged