added assignment4 Javier Mora
FacultadInformatica-LinkedData/Curso2022-2023-ODKG pull request #159
Opened 2022-10-02 17:37 UTC by lndulgence

2022-10-02 17:42 UTC, dgarijo commented on Assignment4/JavierMora-e22a355/Task07.py
> +
Missing 7.1 ... 7.3 in rdflib

2022-10-02 17:42 UTC, dgarijo requested changes
Solutions are ok, but missing somemandatory exercises

2022-10-03 08:43 UTC, lndulgence commented on Assignment4/JavierMora-e22a355/Task07.py
> +
Added the missing cells (Sorry!)

2022-10-03 13:14 UTC, dgarijo approved these changes

2022-10-03 13:14 UTC, merged