Tasks 6 and 7, Alberto Gómez Jiménez
FacultadInformatica-LinkedData/Curso2022-2023-ODKG pull request #170
Opened 2022-10-03 10:22 UTC by KairoSagewing5

2022-10-03 13:40 UTC, dgarijo requested changes

2022-10-03 13:40 UTC, dgarijo commented on Assignment4/KairoSagewing5-22a292/task06.py
> +!pip install rdflib
this is notebook magic, it won't work in python

2022-10-03 13:40 UTC, dgarijo commented on Assignment4/KairoSagewing5-22a292/task06.py
> +g.add((ns.JohnSmith, vcard.Work, Literal('UPM', datatype = XSD.string)))
You have to add UPM as an entity, not a literal.

2022-10-03 13:40 UTC, dgarijo commented on Assignment4/KairoSagewing5-22a292/task06.py
> +g.add((ns.JohnSmith, vcard.Work, Literal('UPM', datatype = XSD.string)))
also vcard does not define the property "Work". Define your own

2022-10-03 13:40 UTC, dgarijo commented on Assignment4/KairoSagewing5-22a292/task07.py
> +      ?Persons RDF:type ?SubSub.
This does not cover more than 3 levels in the taxonomy. Use * to chain subClassOf properties and retrieve all of them

2022-10-03 13:40 UTC, dgarijo commented on Assignment4/KairoSagewing5-22a292/task07.py
> +      ?Persons RDF:type ?SubSub.
same as above

2022-10-03 19:32 UTC, KairoSagewing5 commented
The requested changes are done now.

2022-10-04 11:01 UTC, dgarijo commented
You are missing exercises 7.1, 7.2 and 7.3 in rdflib

2022-10-04 11:21 UTC, KairoSagewing5 commented
I don't think so? I see the three Tasks done in the "File Changes" tab. Maybe I'm wrong, but I've tried to clone the repository again just to check, and I see the file [task07.py] with the Tasks done.

2022-10-04 16:00 UTC, dgarijo commented
You are solving the exercises using SPARQL, but not in rdflib. If so, indicate the lines, please.

2022-10-04 20:22 UTC, KairoSagewing5 commented
You were completely right, sorry, I overlooked that part. I've updated the file with the RDFLib part. 
Also, I kept the RDFLib part simple because I could not figure a simple way to iterate queries for subClassOf of chained sub classes (Like with the * in SPARQL) If possible, I would like to hear how to do that.

2022-10-04 20:57 UTC, dgarijo approved these changes

2022-10-04 20:57 UTC, merged

2022-10-04 20:58 UTC, dgarijo commented
You can do it with a recursive function.