Assignment4-Javier Montoya
FacultadInformatica-LinkedData/Curso2022-2023-ODKG pull request #179
Opened 2022-10-03 19:47 UTC by Javiguti

Added tasks 6 and 7

2022-10-04 15:55 UTC, dgarijo commented
Task7 is incomplete.

2022-10-04 21:03 UTC, Javiguti commented
added task7

2022-10-05 14:29 UTC, dgarijo requested changes

2022-10-05 14:29 UTC, dgarijo commented on Assignment4/Javiguti-22A247/task6.py
> +!pip install rdflib
won't work in Python. This is notebook magic

2022-10-05 14:29 UTC, dgarijo commented on Assignment4/Javiguti-22A247/task7.py
> +  for s2,p2,o2 in g.triples((None, RDF.type, subClass)):
where is the subCalss variable coming from?

2022-10-05 14:29 UTC, dgarijo commented on Assignment4/Javiguti-22A247/task7.py
> +  for s2,p2,o2 in g.triples((None, RDF.type, subClass)):
You have not run this script/notebook...

2022-10-05 21:24 UTC, Javiguti commented
Hey, Im sorry, I did not save before the final changes and uploaded the incomplete one. Sorry! it should work now

2022-10-06 09:37 UTC, dgarijo approved these changes

2022-10-06 09:37 UTC, merged