Added the corresponding data for Assigment1
FacultadInformatica-LinkedData/Curso2022-2023-ODKG pull request #257
Opened 2022-10-13 09:05 UTC by ErHulio

2022-10-29 19:56 UTC, dgarijo requested changes
There are incorrect things. I also believe the deadline for assignment 4 has passed.

2022-10-29 19:56 UTC, dgarijo commented on Assignment4/ErHulio-z170088/task06.py
> +g.add((ns.JohnSmith, VCARD.worksAt, ns.UPM))
vcard does not definde the property worksAt. You have to search for another vocabulary or define your own property

2022-10-29 19:56 UTC, dgarijo commented on Assignment4/ErHulio-z170088/task07.py
> +    ?Subject2 rdf:type ns:Researcher.
This is printing all the entities which are of type person and researcher. Not those from all subclasses of person

2022-10-29 19:56 UTC, dgarijo commented on Assignment4/ErHulio-z170088/task07.py
> +    print(s, x, y)
There are more sublcasses of person. You have to do this method without listing them manually

2022-10-29 19:56 UTC, dgarijo commented on Assignment4/ErHulio-z170088/task07.py
> +    ?Subject2 ?Predicate2 ?Object2.
same as above

2022-11-15 13:17 UTC, ocorcho commented
Closing as comments have not been taken into account for a long period.

2022-11-15 13:17 UTC, closed without merging